pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Install Dependencies') {
      steps {
        dir('simple-node-test') {
          sh 'npm install'
        }
      }
    }
    stage('Run Tests') {
      steps {
        dir('simple-node-test') {
          sh 'npm test'
        }
      }
    }
  }
}
